version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data
  pyparsers:
    image: python:3.9
    container_name: pyparsers
    tty: true
    volumes:
      - pyparsers_data:/home/
    environment:
      API_KEY: ${API_KEY}
      MONGO_PUBLIC_IP: ${MONGO_PUBLIC_IP}
      MONGO_PORT: ${MONGO_PORT}
      SYMBOLS: ${SYMBOLS}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    command: >
      bash -c '
        apt update -y && \
        apt install -y vim && \
        python3 -m venv /home/venv/ && \
        python3 -m pip install --upgrade pip && \
        source /home/venv/bin/activate && \
        pip3 install -r /home/requirements.txt && \
        python /home/main.py'

volumes:
  mongo_data:
    external: true
  pyparsers_data:
    external: true